# Generated by Django 5.1.1 on 2024-09-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0002_alter_videorecording_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('attended', 'attended'), ('not_attended', 'not_attended')], max_length=20, null=True),
        ),
    ]
