# Generated by Django 5.1.1 on 2026-02-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screening", "0004_facereference"),
    ]

    operations = [
        migrations.AddField(
            model_name="facereference",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facereference",
            name="webcam_capture",
            field=models.ImageField(
                blank=True, null=True, upload_to="webcam_captures/"
            ),
        ),
    ]
