# Generated by Django 5.1.1 on 2026-02-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screening", "0005_facereference_verified_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facereference",
            name="webcam_face_crop",
            field=models.ImageField(
                blank=True, null=True, upload_to="webcam_face_crops/"
            ),
        ),
    ]
