# Generated by Django 5.1.1 on 2024-09-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_app', '0004_resumedetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedetails',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
