# Generated by Django 5.1.1 on 2024-09-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_app', '0005_resumedetails_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumedetails',
            name='passing_out_year',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
    ]
