# Generated by Django 5.1.1 on 2024-09-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_app', '0006_alter_resumedetails_passing_out_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedetails',
            name='cert_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resumedetails',
            name='exp_achieve_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resumedetails',
            name='project_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resumedetails',
            name='tech_skill_score',
            field=models.FloatField(default=0),
        ),
    ]
