# Generated by Django 5.1.1 on 2024-09-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_app', '0007_resumedetails_cert_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedetails',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
