# Generated by Django 5.1.1 on 2024-09-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_app', '0008_resumedetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumedetails',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], max_length=20),
        ),
    ]
