# Generated by Django 5.1.1 on 2025-06-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_app', '0010_resumedetails_video_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumedetails',
            name='Cgpa',
            field=models.CharField(default=0, max_length=3, null=True),
        ),
    ]
